# Default configuration for extension with alias: "ux_icons"
ux_icons:

    # The local directory where icons are stored.
    icon_dir:             '%kernel.project_dir%/assets/icons'


    # Default attributes to add to all icons.
    default_icon_attributes:

        # Default:
#        fill:                currentColor
        fill: red
        width: 16px
        height: 16px

        # Example:
        # class:               icon

    # Icon sets configuration.
    icon_sets:

        # Prototype: the icon set prefix (e.g. "acme")
        prefix:

            # The local icon set directory path.
            # (cannot be used with 'alias')
            path:                 ~ # Example: '%kernel.project_dir%/assets/svg/acme'

            # The remote icon set identifier.
            # (cannot be used with 'path')
            alias:                ~ # Example: simple-icons

            # Override default icon attributes for icons in this set.
            icon_attributes:      []

                # Examples:
                # class:               'icon icon-acme'
                # fill:                none

    # Icon aliases (map of alias => full name).
    aliases:              []

        # Examples:
        # dots:                'clarity:ellipsis-horizontal-line'
        # privacy:             'bi:cookie'

    # Configuration for the remote icon service.
    iconify:
        enabled:              true

        # Whether to download icons "on demand".
        on_demand:            true

        # The endpoint for the Iconify icons API.
        endpoint:             'https://api.iconify.design'

    # Ignore error when an icon is not found.
    # Set to 'true' to fail silently.
    ignore_not_found:     false

