<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\BookRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity using data from data/goodreads-books.csv
 */
#[Entity(repositoryClass: BookRepository::class)]
#[MeiliIndex(
    searchable: ['title'],
    filterable: ['languageCode','originalPublicationYear']
)]
final class Book
{
	#[Column(type: Types::INTEGER, nullable: true)]
    #[Id]
	public ?int $bookId = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $goodreadsBookId = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $bestBookId = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $workId = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $booksCount = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $isbn = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $isbn13 = null;

	#[Column(length: 255, nullable: true)]
	public ?string $authors = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $originalPublicationYear = null;

	#[Column(length: 255, nullable: true)]
	public ?string $originalTitle = null;

	#[Column(length: 255, nullable: true)]
	public ?string $title = null;

	#[Column(length: 255, nullable: true)]
	public ?string $languageCode = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $averageRating = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratingsCount = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $workRatingsCount = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $workTextReviewsCount = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings1 = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings2 = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings3 = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings4 = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings5 = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $imageUrl = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $smallImageUrl = null;
}
