<?php

declare(strict_types=1);

namespace App\Entity;

// no unique id in entity, need to handle automatic ids or figure one out.

use App\Repository\CarRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

use Symfony\Component\String\Slugger\AsciiSlugger;
use function Symfony\Component\String\u;

/**
 * @generated by code:entity using data from data/cars.csv
 */
#[Entity(repositoryClass: CarRepository::class)]
#[MeiliIndex(
    primaryKey: 'id',
    filterable: [
        'engineInformationNumberOfForwardGears',
        'engineInformationDriveline',
        'identificationClassification',
        'fuelInformationFuelType',
    ]
)]
final class Car
{
    #[Column(type: Types::INTEGER)]
    #[Id]
    #[GeneratedValue]
    public int $id;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $dimensionsHeight = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $dimensionsLength = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $dimensionsWidth = null;

	#[Column(length: 255, nullable: true)]
	public ?string $engineInformationDriveline = null;

	#[Column(length: 255, nullable: true)]
	public ?string $engineInformationEngineType = null;

	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $engineInformationHybrid = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $engineInformationNumberOfForwardGears = null;

	#[Column(length: 255, nullable: true)]
	public ?string $engineInformationTransmission = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $fuelInformationCityMpg = null;

	#[Column(length: 255, nullable: true)]
	public ?string $fuelInformationFuelType = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $fuelInformationHighwayMpg = null;

	#[Column(length: 255, nullable: true)]
	public ?string $identificationClassification = null;

	#[Column(length: 255, nullable: false)]
	public ?string $identificationID { set(?string $value) => $value ? new AsciiSlugger()->slug($value)->toString(): 'no-id';}

	#[Column(length: 255, nullable: true)]
	public ?string $identificationMake = null;

	#[Column(length: 255, nullable: true)]
	public ?string $identificationModelYear = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $identificationYear = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $engineInformationEngineStatisticsHorsepower = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $engineInformationEngineStatisticsTorque = null;
}
