<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\MetObjectRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 *
 * https://github.com/metmuseum/openaccess
 *
 * @generated by code:entity
 */
#[Entity(repositoryClass: MetObjectRepository::class)]
#[MeiliIndex(
    primaryKey: 'objectID',
    searchable: ['objectName', 'title'],
    filterable: ['accessionYear', 'department','medium','isHighlight','isPublicDomain']
)]
final class MetObject
{
	#[Column(type: Types::INTEGER, nullable: true)]
	#[Id]
	public ?int $objectID = null;

	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $isHighlight = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $accessionNumber = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $accessionYear = null;

	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $isPublicDomain = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $primaryImage = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $primaryImageSmall = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $additionalImages = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $constituents = null;

	#[Column(length: 255, nullable: true)]
	public ?string $department = null;

	#[Column(length: 255, nullable: true)]
	public ?string $objectName = null;

	#[Column(length: 255, nullable: true)]
	public ?string $title = null;

	#[Column(length: 255, nullable: true)]
	public ?string $culture = null;

	#[Column(length: 255, nullable: true)]
	public ?string $period = null;

	#[Column(length: 255, nullable: true)]
	public ?string $dynasty = null;

	#[Column(length: 255, nullable: true)]
	public ?string $reign = null;

	#[Column(length: 255, nullable: true)]
	public ?string $portfolio = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistRole = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistPrefix = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistDisplayName = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistDisplayBio = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistSuffix = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistAlphaSort = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistNationality = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $artistBeginDate = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $artistEndDate = null;

	#[Column(length: 255, nullable: true)]
	public ?string $artistGender = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $artistWikidataURL = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $artistULANURL = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $objectDate = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $objectBeginDate = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $objectEndDate = null;

	#[Column(length: 255, nullable: true)]
	public ?string $medium = null;

	#[Column(length: 255, nullable: true)]
	public ?string $dimensions = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $measurements = null;

	#[Column(length: 255, nullable: true)]
	public ?string $creditLine = null;

	#[Column(length: 255, nullable: true)]
	public ?string $geographyType = null;

	#[Column(length: 255, nullable: true)]
	public ?string $city = null;

	#[Column(length: 255, nullable: true)]
	public ?string $state = null;

	#[Column(length: 255, nullable: true)]
	public ?string $county = null;

	#[Column(length: 255, nullable: true)]
	public ?string $country = null;

	#[Column(length: 255, nullable: true)]
	public ?string $region = null;

	#[Column(length: 255, nullable: true)]
	public ?string $subregion = null;

	#[Column(length: 255, nullable: true)]
	public ?string $locale = null;

	#[Column(length: 255, nullable: true)]
	public ?string $locus = null;

	#[Column(length: 255, nullable: true)]
	public ?string $excavation = null;

	#[Column(length: 255, nullable: true)]
	public ?string $river = null;

	#[Column(length: 255, nullable: true)]
	public ?string $classification = null;

	#[Column(length: 255, nullable: true)]
	public ?string $rightsAndReproduction = null;

	#[Column(length: 255, nullable: true)]
	public ?string $linkResource = null;

	#[Column(length: 255, nullable: true)]
	public ?string $metadataDate = null;

	#[Column(length: 255, nullable: true)]
	public ?string $repository = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $objectURL = null;

	#[Column(type: Types::JSON, nullable: true, options: ['jsonb' => true])]
	public ?array $tags = null;

	#[Column(length: 2048, nullable: true)]
	public ?string $objectWikidataURL = null;

	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $isTimelineWork = null;

	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $galleryNumber = null;
}
