<?php

declare(strict_types=1);

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Symfony\Component\Validator\Constraints\Url;

/**
 * @generated by code:entity
 */
#[Entity(repositoryClass: App\Repository\MovieRepository::class)]
final class Movie
{
	#[Column(type: Types::INTEGER)]
	#[Id]
	private ?int $id = null;

	#[Column(length: 255)]
	private ?string $imdb_id = null;

	#[Column(length: 255)]
	private ?string $popularity = null;

	#[Column(length: 255)]
	private ?string $budget = null;

	#[Column(length: 255)]
	private ?string $revenue = null;

	#[Column(length: 255)]
	private ?string $original_title = null;

	#[Column(length: 255)]
	private ?string $cast = null;

	#[Column(length: 255)]
	private ?string $homepage = null;

	#[Column(length: 255)]
	private ?string $director = null;

	#[Column(length: 255)]
	private ?string $tagline = null;

	#[Column(length: 255)]
	private ?string $keywords = null;

	#[Column(length: 255)]
	private ?string $overview = null;

	#[Column(length: 255)]
	private ?string $runtime = null;

	#[Column(length: 255)]
	private ?string $genres = null;

	#[Column(length: 255)]
	private ?string $production_companies = null;

	#[Column(length: 255)]
	private ?string $release_date = null;

	#[Column(length: 255)]
	private ?string $vote_count = null;

	#[Column(length: 255)]
	private ?string $vote_average = null;

	#[Column(length: 255)]
	private ?string $release_year = null;

	#[Column(length: 255)]
	private ?string $budget_adj = null;

	#[Column(length: 255)]
	private ?string $revenue_adj = null;
}
