<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\WamRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\Fields;
use Survos\MeiliBundle\Metadata\MeiliIndex;
use Symfony\Component\Serializer\Attribute\Groups;

/**
 * @generated by code:entity
 */
#[Entity(repositoryClass: WamRepository::class)]
#[MeiliIndex(
    persisted: new Fields(
       groups: ['wam.read', 'wam.searchable']
    ),
    searchable: new Fields(
        groups: ['wam.searchable']
    ),
    filterable: ['keywords', 'condition', 'creator'],
    embedders: ['small_wam', 'large_wam']
)]
final class Wam
{
	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.searchable'])]
	public ?string $title = null;

	#[Column(nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $url = null;

	#[Column(length: 2048, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $wamImage = null;

	#[Column(type: Types::STRING, nullable: true)]
	public ?string $accessionNumber = null;

	#[Column(length: 255, nullable: true)]
	public ?string $cataloguer = null;

	#[Column(length: 255, nullable: true)]
	public ?string $collection = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.searchable'])]
	public ?string $description = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
    #[Groups(['wam.read','wam.searchable'])]
	public ?array $keywords = null;

	#[Column(length: 255, nullable: true)]
	public ?string $location = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.searchable'])]
	public ?string $notes = null;

	#[Column(length: 255, nullable: true)]
    #[Id]
    #[Groups(['wam.read'])]
	public ?string $registrationNumber = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $subject = null;

//	#[Column(length: 2048, nullable: true)]
    // can't access this link
	public ?string $thumbnail = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $condition = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $creator = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $digitalId = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $medium = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $mediumFormat = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $notes2 = null;

	#[Column(length: 255, nullable: true)]
	public ?string $originalLegalBroker = null;

	#[Column(length: 255, nullable: true)]
    #[Groups(['wam.read'])]
	public ?string $state = null;
}
